### ISSUE TITLE
Docs don't match current version

### ISSUE THREAD

**Issue by inferiorhumanorgans** [sharazam/printpdf#103]
Per the top level README:

```toml
[dependencies]
printpdf = "0.3.2"
```
I've not checked to see if there are additional references to 0.3.
