### ISSUE TITLE
Enable some features for docs.rs?

### ISSUE THREAD

**Issue by Shadlock0133** [sharazam/printpdf#116]
Currently, docs.rs doesn't show Image functions which are behind a "embedded_images" feature flag. Here is docs.rs's docs on how to enable it: https://docs.rs/about/metadata. I think adding this to Cargo.toml should work:
```toml
[package.metadata.docs.rs]
features = ["embedded_images"]
```
